
version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

#  postgres:
#    image: postgres:15
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: test
#      POSTGRES_PASSWORD: test
#      POSTGRES_DB: pocdb
#    volumes:
#      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
